stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - apk add podman
    - podman info
    # TODO: Registry credentials
    # - podman login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
  script:
    - podman build --build-arg JDK=17 -t ghcr.io/unstoppablemango/my-image:latest ./actions/build-image
    # - podman push ghcr.io/unstoppablemango/my-image:latest

deploy:
  stage: deploy
  image: alpine/helm
  before_script:
    - apk add helm
  script:
    - helm version
