name: Build Image
description: Build a container image using Podman
inputs:
  name:
    description: Name of the image to deploy
    required: true
  tag:
    description: Tag of the image to deploy
    required: false
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Setup helm
      uses: azure/setup-helm@v4

    - name: Deploy Helm Chart
      shell: bash
      run: |
        helm upgrade my-java-app ./actions/deploy-image/charts/java-app \
          --install \
          --namespace my-java-project \
          --create-namespace \
          --set image.repository=ghcr.io/unstoppablemango/${{ inputs.name }} \
          --set image.tag=${{ inputs.tag }}
