name: Build Image
description: Build a container image using Podman
inputs:
  jdk:
    description: JDK version to use for the build environment
    required: false
    default: '17'

runs:
  using: composite
  steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    - name: Test
      run: kubectl get pods -A
      shell: bash
