name: CI

on:
  push:
    branches: [ gharc ]

jobs:
  build:
    runs-on: arc-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build container image
        uses: ./actions/build-image
        with:
          jdk: '17'
