name: CI

on:
  push:
    branches: [ tutorial ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build container image
        uses: ./actions/build-image
        with:
          name: openshift-lab
          github-username: unstoppablemango
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy container image
        uses: ./actions/deploy-image
